= Fraction Authoring

== Introduction

The composable pieces of WildFly Swarm are called _fractions_. Each fraction
starts with a single Maven-addressable artifact which ultimately brings in
others.

We refer to the various pieces as

- _parent_: The top-most `pom.xml` to aggregate the build of the 
  lower portions.

- _root_: The user-referenced piece that provides BOM-like capabilities
  in order to make all the functionality available.

- _api_: Transitively brought in from the _root_, and provides whatever
  user-facing API is required for configuring the fraction.

- _runtime_: The back-end portion of the fraction (if required) that
  provides runtime-support.

- _modules_: An artifact containing a tree of `module.xml` files used
  by JBoss Modules in order to support our modular classloading.

Each of the above is typically laid out as a multi-project Maven tree.

For a hypothetical _Jolokia_ fraction:

[source,shell]
----
jolokia/
  pom.xml                    # <1>
  exposed-components.json    # <2>
  jolokia/
    pom.xml                  # <3>
  api/
    pom.xml                  # <4>
    src/...
  runtime/
    pom.xml                  # <5>
    src/...
  modules/
    pom.xml                  # <6>
    src/...
----
<1> The `-parent` aggregator POM.
<2> Defines the components to be included in WildFly Swarm BOM.
<3> The simply-named _root_ artifact which can also act as a BOM.
<4> The `-api` artifact which exposes any user-facing APIs.
    along with transitive dependencies of relevant specifications.
    It includes the `*Fraction.java` class.
<5> The `-runtime` artifact which provides from back-end configuration
    of the WildFly Swarm server based upon the fraction.
<6> The `-modules` artifact to bring in a JBoss-Modules module tree
    of modules.

== The Parent

At the top of the tree, the `pom.xml` is the `-parent` artifact simply
to arrange Maven `<dependencyManagement>`, configure plugins and aggregate
the builds of the lower projects.

It is useful to set at least a pair of properties, specifying the version
of the WildFly Swarm SPI and fraction-plugin being used:

[source,xml]
----
<properties>
  <version.swarm.spi>1.0.0.Beta3</version.swarm.spi>
  <version.swarm.fraction-plugin>1.0.0.Beta2</version.swarm.fraction-plugin>
</properties>
----

The SPI should be mixed into the `<dependencyManagement>` section, imported
as a BOM.  Additionally, the components of the fraction itself can be managed
in order to make cross-dependency specification in the lower-level `pom.xml`
files easier:

[source,xml]
----
<dependencyManagement>
  <dependencies>
    <dependency>                                <!--1-->
      <groupId>org.wildfly.swarm</groupId>
      <artifactId>spi</artifactId>
      <version>${version.swarm.spi}</version>
      <type>pom</type>
      <scope>import</scope>
    </dependency>

    <dependency>                                <!--2-->
      <groupId>org.wildfly.swarm</groupId>
      <artifactId>jolokia</artifactId>
      <version>1.0.0.Beta3-SNAPSHOT</version>
    </dependency>
    <dependency>
      <groupId>org.wildfly.swarm</groupId>
      <artifactId>jolokia-api</artifactId>
      <version>1.0.0.Beta3-SNAPSHOT</version>
    </dependency>
    <dependency>
      <groupId>org.wildfly.swarm</groupId>
      <artifactId>jolokia-modules</artifactId>
      <version>1.0.0.Beta3-SNAPSHOT</version>
    </dependency>
    <dependency>
      <groupId>org.wildfly.swarm</groupId>
      <artifactId>jolokia-runtime</artifactId>
      <version>1.0.0.Beta3-SNAPSHOT</version>
    </dependency>
  </dependencies>
</dependencyManagement>
----
<1> Import the SPI BOM
<2> Manage all other components of this fraction

Additionally, the `wildfly-swarm-fraction-plugin` should be configured
within the parent `pom.xml` so that it fires for every sub-module:

[source,xml]
----
<build>
  <plugins>
    <plugin>
      <groupId>org.wildfly.swarm</groupId>
      <artifactId>wildfly-swarm-fraction-plugin</artifactId>
      <version>${version.swarm.fraction-plugin}</version>
      <executions>
        <execution>
          <phase>process-classes</phase>
          <goals>
            <goal>process</goal>
          </goals>
        </execution>
      </executions>
    </plugin>
  </plugins>
</build>
----

Making a fraction available in the WildFly Swarm BOM requires a `exposed-components.json` to be defined:

[source,json]
----
{"Jolokia": [                                                     <!--1-->
  {"name": "jolokia",              "doc": "jolokia-api"},         <!--2-->
  {"name": "jolokia-modules"},                                    <!--3-->
]}
----
<1> Define the name to be used within generated javadocs
<2> Define `name` as the Root module and `doc` as the API module
<3> Define the `name` for the Modules module

== The Root

In our above example, `jolokia/jolokia/pom.xml` lives by itself, with no 
related source, but ties together the remaining bits, and is the artifact 
referenced by a user's application.  This is the _root_ artifact.

The project, while it has `<packaging>jar</packaging>`, does not include
any source.  Instead it provides transitive dependencies to the 
various other bits of the fraction, along with transitive dependencies
to any other entire fractions required by this one.

Jolokia, for instance, is deployed as a WAR file, and thus this fraction
requires the `undertow` fraction also.

[source,xml]
----
<project xmlns="http://maven.apache.org/POM/4.0.0" 
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>org.wildfly.swarm</groupId>
    <artifactId>jolokia-parent</artifactId>
    <version>1.0.0.Beta3-SNAPSHOT</version>
    <relativePath>../</relativePath>
  </parent>

  <groupId>org.wildfly.swarm</groupId>
  <artifactId>jolokia</artifactId>        <!--1-->

  <name>WildFly Swarm: Jolokia</name>
  <description>WildFly Swarm: Jolokia</description>

  <packaging>jar</packaging>

  <dependencies>
    <dependency>                          <!--2-->
      <groupId>org.wildfly.swarm</groupId>
      <artifactId>jolokia-api</artifactId>
    </dependency>
    <dependency>                          <!--3-->
      <groupId>org.wildfly.swarm</groupId>
      <artifactId>jolokia-modules</artifactId>
    </dependency>
    <dependency>                          <!--4-->
      <groupId>org.wildfly.swarm</groupId>
      <artifactId>jolokia-runtime</artifactId>
      <scope>provided</scope>
    </dependency>

    <dependency>                          <!--5-->
      <groupId>org.wildfly.swarm</groupId>
      <artifactId>undertow</artifactId>
    </dependency>

  </dependencies>

</project>
----
<1> The `artifactId` is the simple, user-referencable name of the fraction.
<2> The `-api` artifact is implicitly `<scope>compile</scope>`
<3> The `-modules` artifact is implicitly `<scope>compile</scope>`
<4> The `-runtime` artifact is explicitly `<scope>provided</scope>`
<5> Any other required fractions are referenced by their simple _root_
    `artifactId` with an implicit `<scope>compile</scope>`.

Please note, the versions of each dependency are managed by the `-parent` POM
described in the previous section.

== API

The `-api` artifact represents any user-facing configuration API, including
the any relevant `*Fraction.java` class.  

=== The `*Fraction.java`

If the fraction includes configuration capabilities, or otherwise alters
the runtime system through deployments or adjustments to the server, it
should include an implement of `org.wildfly.swarm.spi.api.Fraction`.

Any opaque POJO configuration details that are required may be added
the implementation, and will be passed to the back-end runtime portion
during server boot-up to control configuration.

In the event that no particular configuration values are required, a
basic no-op `*Fraction.java` may be created.

[source,java]
----
package com.mycorp.cheese;

import java.util.Set;
import java.util.HashSet;
import org.wildfly.swarm.spi.api.Fraction;

public class CheeseFraction implements Fraction {

  // arbitrary configuration parameters are allowed

  public void cheese(String type) {
    this.cheeses.add( type );
  }

  public void cheeses(Set<String> types) {
    this.cheeses.addAll( types );
  }

  public Set<String> cheeses() {
    return this.cheeses;
  }

  private Set<String> cheeses = new HashSet<>();
}
----

=== Exposing Transitive Dependencies to Users' Applications

If your fraction aims to enable some API or specification beyond the fraction
itself (such as enabling usage of `javax.jms` for instance), the `-api` `pom.xml`
should include such dependency as `<scope>compile</scope>`.  In the root
of the `pom.xml`, on the `<project>` element, you need to add an `xmlns` for
the WildFly Swarm XML namespace, and also mark the relevant `<dependency>` as
below:

[source,xml]
----
<project xmlns:swarm="http://wildfly-swarm.io/">
  ...
  <dependencies>

    ...

    <dependency swarm:scope="provided">
      <groupId>org.jboss.spec.javax.jms</groupId>
      <artifactId>jboss-jms-api_2.0_spec</artifactId>
    </dependency>
  </dependencies>
  ...
</project>
----

This allows for a user to reference only your fraction, and implicitly
receive the JMS specification classes on their classpath.

By marking it with `swarm:scope`, it enables the WildFly Swarm plugin to
know that the specification artifact is _actually_ provided at runtime
by the server, and shouldn't be considered a application dependency.

== Runtime

The `-runtime` artifact is responsible for taking the above `Fraction` implementation
and effecting changes to the runtime server based upon its existance and configuration
values.

For every `*Fraction.java`, there should exist a matching `*Configuration.java`.  For the
simplest cases, the `*Configuration.java` can actually be synthesized based upon 
Java annotations on the `*Fraction.java` itself.  If that suffices, the entire
`-runtime` artifact may be avoided.

=== Using only annotations within `-api`

Usually only useful for fractions that are based upon the WildFly `config-api`
and represent aspects of a usual `standalone.xml`

The `org.wildfly.swarm.spi.api.annotations.Configuration` annotation may be applied
directly to a `Fraction` implementation, with the following properties optionally set:

[cols="2", options="header"]
|===
|Name
|Description

|`extension`
|The WildFly module holding the extension. Maps directly to the `<extension>` element in `standalone.xml`

|`marshal`
|Boolean indicating if the `Fraction` should be marshalled using the `config-api` marshaller

|`ignorable`
|Boolean indicating if the fraction may be entirely ignored. I don't remember why we would want to. But it's there.

|`parserFactoryClassName`
|Name of the class (as a string) of the `ParserFactory` from the `-runtime` portion of the fraction
 to allow for parsing of `standalone.xml` fragments for this fraction.
|===

== Modules

The `-modules` artifact is required to handle the variety of classloading aspects of each fraction.
There are typically 3 modules in the tree related to the `-api` and `-runtime` portions of the fraction.
General convention requires that the base module name is exactly the same as the package portion
of the `*Fraction` implementation.

For instance, if you have `com.mycorp.cheese.CheeseFraction`, then the base module name should be
`com.mycorp.cheese`.  

=== The `:main` slot

=== The `:api` slot

=== The `:runtime` slot
