= Implementation Details

This chapter mostly serves as a road-map for users who are curious about the actual inner workings of WildFly Swarm.

== `_myapp_-swarm.jar`

The layout of the generated `_myapp_-swarm.jar` looks roughly like:

`wildfly-swarm.properties` :: File containing the version of WildFly Swarm used in the construction.

`META-INF/wildfly-swarm.properties` :: File containing all user-specified (or default) properties to be used when executing the uberjar.  For example:
+
[source,text]
----
#Generated by WildFly Swarm
#Tue Aug 25 11:38:12 BRT 2015
jboss.socket.binding.port-offset=3
swarm.logstash.hostname=localhost
wildfly.swarm.context.path=/
jboss.bind.address=127.0.0.1
java.net.preferIPv4Stack=true
jboss.node.name=booker-pricing
wildfly.swarm.app.artifact=booker-pricing-1.0.0.Alpha01-SNAPSHOT.jar
swarm.logstash.port=8000
----

`META-INF/wildfly-swarm-bootstrap.conf`:: Lists all WildFly Swarm module dependencies in Maven GAV format.  For example:
+
[source,text]
----
org.wildfly.swarm:wildfly-swarm-logging-modules:1.0.0.Alpha4
org.wildfly.swarm:wildfly-swarm-security-modules:1.0.0.Alpha4
org.wildfly.swarm:wildfly-swarm-hystrix:1.0.0.Alpha4
org.wildfly.swarm:wildfly-swarm-rxnetty:1.0.0.Alpha4
org.wildfly.swarm:wildfly-swarm-rxjava:1.0.0.Alpha4
org.wildfly.swarm:wildfly-swarm-ee-modules:1.0.0.Alpha4
org.wildfly.swarm:wildfly-swarm-logstash-modules:1.0.0.Alpha4
org.wildfly.swarm:wildfly-swarm-ribbon-secured-modules:1.0.0.Alpha4
----

`META-INF/wildfly-swarm-dependencies.conf':: Lists all applications dependencies (WildFly Swarm and application-specific).  For example:
+
[source,text]
----
org.wildfly.swarm:wildfly-swarm-undertow:1.0.0.Alpha4
org.wildfly.swarm:wildfly-swarm-io:1.0.0.Alpha4
org.wildfly.swarm:wildfly-swarm-clustering:1.0.0.Alpha4
javax.json:javax.json-api:1.0
org.wildfly.swarm:wildfly-swarm-ribbon-secured:1.0.0.Alpha4
org.wildfly.swarm:wildfly-swarm-ee-modules:1.0.0.Alpha4
org.wildfly.swarm:wildfly-swarm-keycloak:1.0.0.Alpha4
org.ow2.asm:asm-all:5.0.4
org.wildfly.swarm:wildfly-swarm-msc-modules:1.0.0.Alpha4
org.wildfly.swarm:wildfly-swarm-security:1.0.0.Alpha4
org.jboss.spec.javax.enterprise.concurrent:jboss-concurrency-api_1.0_spec:1.0.0.Final
org.jboss.spec.javax.annotation:jboss-annotations-api_1.2_spec:1.0.0.Final
org.jboss.msc:jboss-msc:1.2.6.Final
----

`m2repo/` :: Maven-style repository of all jars

`modules/` :: JBoss-Modules tree of `module.xml` files which reference jars by Maven GAV
