= Implementation Details

This chapter mostly serves as a road-map for users who are curious about the actual inner workings of WildFly Swarm.

== Uberjar Layout

The layout of the generated `_myapp_-swarm.jar` looks roughly like:

`wildfly-swarm.properties` :: File containing the version of WildFly Swarm used in the construction.

`META-INF/wildfly-swarm.properties` :: File containing all user-specified (or default) properties to be used when executing the uberjar.  For example:
+
[source,text]
----
#Generated by WildFly Swarm
#Tue Aug 25 11:38:12 BRT 2015
jboss.socket.binding.port-offset=3
swarm.logstash.hostname=localhost
wildfly.swarm.context.path=/
jboss.bind.address=127.0.0.1
java.net.preferIPv4Stack=true
jboss.node.name=booker-pricing
wildfly.swarm.app.artifact=booker-pricing-1.0.0.Alpha01-SNAPSHOT.jar
swarm.logstash.port=8000
----

`META-INF/wildfly-swarm-bootstrap.conf`:: Lists all WildFly Swarm module dependencies in Maven GAV format.  For example:
+
[source,text]
----
org.wildfly.swarm:wildfly-swarm-logging-modules:1.0.0.Alpha4
org.wildfly.swarm:wildfly-swarm-security-modules:1.0.0.Alpha4
org.wildfly.swarm:wildfly-swarm-hystrix:1.0.0.Alpha4
org.wildfly.swarm:wildfly-swarm-rxnetty:1.0.0.Alpha4
org.wildfly.swarm:wildfly-swarm-rxjava:1.0.0.Alpha4
org.wildfly.swarm:wildfly-swarm-ee-modules:1.0.0.Alpha4
org.wildfly.swarm:wildfly-swarm-logstash-modules:1.0.0.Alpha4
org.wildfly.swarm:wildfly-swarm-ribbon-secured-modules:1.0.0.Alpha4
----

`META-INF/wildfly-swarm-application.conf` :: Lists all application dependencies as JBoss-Module names or Maven GAVs.  For example:
+
[source,text]
----
module:org.wildfly.swarm.keycloak
module:org.wildfly.swarm.netflix.ribbon.secured
module:org.wildfly.swarm.security
module:org.wildfly.swarm.logstash
module:org.wildfly.swarm.netflix.ribbon
gav:org.wildfly.swarm:wildfly-swarm-undertow:1.0.0.Alpha4
gav:org.wildfly.swarm:wildfly-swarm-io:1.0.0.Alpha4
gav:io.netty:netty-transport:4.0.27.Final
gav:io.netty:netty-buffer:4.0.26.Final
gav:org.wildfly.swarm:wildfly-swarm-clustering:1.0.0.Alpha4
gav:javax.json:javax.json-api:1.0
gav:io.reactivex:rxnetty:0.4.9
----

`META-INF/MANIFEST.MF` :: Standard Java archive manifest which specifies the WildFly Swarm bootstrap `Main-Class` along with tracking the user-provided main class.  For example:
+
[source,text]
----
Main-Class: org.wildfly.swarm.bootstrap.Main
Wildfly-Swarm-Main-Class: org.mycorp.myapp.Main
----

`m2repo/` :: Maven-style repository of all jars

`modules/` :: JBoss-Modules tree of `module.xml` files which reference jars by Maven GAV
