= Swagger

== Introduction
Swagger is a formal specification for a language-agnostic interface to REST APIs. This interface lets both humans and computers understand an API's capabilities such that a consumer of the API can interact with the service. In simple terms, swagger is a JSON representation of a RESTful API, typically made available over HTTP at `/swagger.json`.

A simple `swagger.json` will look something like this.

[code,json]
----
{
    "swagger":"2.0",
    "info":{},
    "basePath":"/",
    "tags":[{"name":"time"}],
    "paths":{
        "/time/now":{
            "get":{
                "tags":["time"],
                "summary":"Get the current time",
                "description":"Returns the time as a string",
                "operationId":"get",
                "produces":["application/json"],
                "parameters":[],
                "responses":{
                    "200":{
                        "description":"successful operation",
                        "schema":{"type":"string"}
                    }
                }
            }
        }
    }
}
----

WildFly Swarm provides a `swagger` fraction that enables JAX-RS API developers to easily publish a `/swagger.json` describing the API.

To learn more about Swagger's capabilities, see the http://swagger.io/[Swagger website].

== Configuration
To enable Swagger in your application, you need to add a dependency to your `pom.xml`.

[source,xml]
----
<dependency>
  <groupId>org.wildfly.swarm</groupId>
  <artifactId>swagger</artifactId>
</dependency>
----

== Usage
The `swagger` fraction works by utilizing does most of the configuration required, but you still need to tell Swagger what package(s) to scan.