= JBoss Forge Add-on

JBoss Forge is a *software development tool* that extends your IDE, providing wizards and extensions (add-ons) for different technologies and solutions. Try JBoss Forge by downloading it at http://forge.jboss.org.

The Wildfly Swarm team provides an add-on that eases the user experience on Swarm.

== Installation

=== From Forge CLI:

[source,shell]
----
addon-install-from-git --url https://github.com/forge/wildfly-swarm-addon.git
----

=== From Eclipse/JBoss Developer Studio:

- Press Ctrl (Or Command if you are on OSX) + 4 and select the `Install an Addon from GIT` option.
- Enter `https://github.com/forge/wildfly-swarm-addon.git` as the url and press "Finish"

=== From IntelliJ IDEA:

- Press Ctrl (Or Command if you are on OSX) + Alt + 4 and select the `Install an Addon from GIT` option.
- Enter `https://github.com/forge/wildfly-swarm-addon.git` as the url and press "Finish"

=== From Netbeans:

- Go to the Quick Search field in the upper right corner and type `Install an Addon from GIT`.
- Enter `https://github.com/forge/wildfly-swarm-addon.git` as the url and press "Finish"


== Features
Wildfly-Swarm Setup command::
Using the Forge shell, navigate to a Java EE project, or create one using the `project-new --named demo --stack JAVA_EE_7` command and type the following command if you're in shell.
+
[source,java]
----
wildfly-swarm-setup
----
+
It should read `Wildfly-Swarm: Setup` if you're in a GUI environment:
+
This will make the `wildfly-swarm-maven` plugin to be installed in your project and the Wildfly Swarm BOM added to the `<dependencyManagement>` section.
+
You may also find some options that will be added to the Wildfly Swarm maven plugin like the context path, the HTTP port and the HTTP Port offset

Wildfly-Swarm Add Fraction::
You can install Wildfly Swarm Fractions by using the command `Wildfly-Swarm: Add Fraction`:
+
[source,java]
----
[demo]$ wildfly-swarm-add-fraction --fractions 
arquillian           camel-jms            datasources          javafx               jdr                  logging              monitor              swagger              vertx                
batch-jberet         camel-jmx            ejb                  jaxrs                jgroups              logstash             mysql                swagger-webapp       webservices          
bean-validation      camel-jpa            ejb-remote           jaxrs-cdi            jmx                  mail                 postgresql           topology-consul      
camel-cdi            camel-mail           h2                   jaxrs-jaxb           jolokia              management           remoting             topology-jgroups     
camel-core           camel-other          hibernate-search     jaxrs-jsonp          jpa                  management-console   resource-adapters    topology-openshift   
camel-cxf            camel-undertow       hibernate-validator  jaxrs-multipart      jsf                  messaging            ribbon               topology-webapp      
camel-ejb            cdi                  hystrix              jaxrs-validator      keycloak             microprofile         ribbon-secured       transactions         
camel-jaxb           cdi-ext              infinispan           jca                  keycloak-server      mod_cluster          spring               undertow             

----
+
NOTE: Installed fractions are not listed when you press <TAB> to auto-complete
